basepath:
inputfile_path:
outputfile_path:

extract_features
method:
extractor_parameters:
    nfeatures:
    nOctaveLayers:
    contrastThreshold:
    edgeThreshold:
    sigma:

match_features
k:

ratio_checks:
clean_keys:
    -
keyword_arguments:
    -

fundamental_matrics
clean_keys:
    -
keyword_arguments:
    -

subpixel_register
clean_keys:
    -
template_size:
threshold:
search_size:
max_x_shift:
max_y_shift:
tiled:
keyword arguments:
    -

suppress:
    clean_keys:
        -
    keyword arguments:
        -
cnet conversion:
    clean_keys:
        -
