language: python
sudo: false

branches:
only:
  - master

python:
  - "3.5"

before_install:

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create a virtual env and install dependencies
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION nose numpy pillow scipy pandas networkx scikit-image sqlalchemy numexpr dill cython pyyaml
  # Activate the env
  - source activate test-env

  # Install the non-conda packages if required, requirements.txt duplicates are ignored
  - conda install -c https://conda.anaconda.org/jlaura opencv3=3.0.0
  - conda install -c menpo cyvlfeat
  - conda config --add channels conda-forge
  - conda install runipy
  - conda install -c https://conda.anaconda.org/conda-forge gdal h5py
  - pip install -r requirements.txt

  # Development installation
  - conda install nose coverage sh anaconda-client
  - pip install coveralls
  - python runipynbs.py

script:
  - nosetests --with-coverage --cover-package=autocnet


after_success:
  - coveralls

    # Straight from the menpo team
  - if [["$TRAVIS_OS_NAME" == "osx"]]; then
      curl -o condaci.py https://raw.githubusercontent.com/menpo/condaci/v0.4.8/condaci.py;
    else
      wget https://raw.githubusercontent.com/menpo/condaci/v0.4.8/condaci.py -O condaci.py;
    fi
    # Build autocnet and push to anaconda cloud
  - python condaci.py setup
  - ~/miniconda/bin/python condaci.py build ./conda

notifications:
  webhooks:
    urls:
 #     - https://webhooks.gitter.im/e/6cbe4b65fff6764ed80f
    on_success: always  
    on_failure: always  
    on_start: never     
  email:
      recipients:
#          - kberry@usgs.gov
#          - dmlytle@usgs.gov
#          - jwbacker@usgs.gov
#          - krodriguez@usgs.gov
      on_success: always
      on_failure: always
      
