language: python
sudo: true

branches:
only:
  - master

python:
  - "3.5"

before_install:
  - sudo apt-get update

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create a virtual env and install dependencies
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION nose gdal numpy scipy pandas networkx
  # Activate the env
  - source activate test-env

  # Install the non-conda packages if required, requirements.txt duplicates are ignored
  - conda install -c osgeo proj4
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

  # Now get OpenCV3 installed
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

  #Grab the source
  - curl -sL http://github.com/Itseez/opencv/archive/3.0.0.zip > opencv.zip
  - curl -sL http://github.com/Itseez/opencv_contrib/archive/3.0.0.zip > opencv_contrib.zip
  - unzip opencv_contrib.zip
  - unzip opencv.zip
  - cd opencv-3.0.0

  # Create a new 'build' folder.
  - mkdir build
  - cd build

  # Set build instructions for Ubuntu distro.
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -D CMAKE_INSTALL_PREFIX=$(python -c "import sys; print(sys.prefix)") -D PYTHON_EXECUTABLE=$(which python ) ..

  # Run 'make' with the 1.5 threads Travis makes available
  - make -j2

  # Install to OS.
  - sudo make install

  # Add configuration to OpenCV to tell it where the library files are located on the file system (/usr/local/lib)
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'

  - sudo ldconfig
  - echo "OpenCV installed."

  # Return to the root
  - cd ../../

  # Might need to link the cv2.so into the env?

script:
  - nosetests --with-coverage --cover-package=autocnet

notifications:
    email:
        recipients:
            - jlaura@usgs.gov
            - kberry@usgs.gov
            - dmlytle@usgs.gov
            - jwbacker@usgs.gov
        on_success: always
        on_failure: always

after_success:
  - coveralls
