package:
  name: autocnet
  version: 0.1.0

source: 
   git_url: https://github.com/USGS-Astrogeology/autocnet.git

requirements:
  build: 
    - python 
    - plio
    - opencv3 3.0.0
    - vlfeat
    - cyvlfeat
    - pillow
    - matplotlib
    - pysal
    - scipy
    - networkx
    - numexpr
    - dill
    - cython
    - pyyaml
  run:
    - python
    - plio
    - opencv3 3.0.0
    - vlfeat
    - cyvlfeat
    - pillow
    - matplotlib
    - pysal
    - scipy
    - networkx
    - numexpr
    - dill
    - cython
    - pyyaml

test:
  imports:
    - autocnet
    - autocnet.graph.network
