language: python
sudo: false
branches:
only:
  - master
env:
  - PYTHON=3.4 DEPS=modern

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes nose gdal
  - conda install --yes conda install -c osgeo proj4 -c https://conda.anaconda.org/osgeo proj4
  - pip install -r requirements.txt --user-mirrors
  - pip install coverage
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=autocnet

  #- cd doc; make pickle; make doctest
notifications:
    email:
        recipients:
            - jlaura@usgs.gov
        on_success: always
        on_failure: always

after_success:
  - coveralls